### ISSUE TITLE
kubeadm 1.7.1 cannot start due to bug

### ISSUE THREAD

**Issue by sandor-nemeth** [Project31/ansible-kubernetes-openshift-pi3#23]
Kubeadm 1.7.1 is broken, when the init would run one'll get an error:

```bash
$ kubeadm init --config /etc/kubernetes/kubeadm.yml                                                                                                                 
[kubeadm] WARNING: kubeadm is in beta, please do not use it for production clusters.            
[init] Using Kubernetes version: v1.7.1         
[init] Using Authorization modes: [Node RBAC]   
[preflight] Running pre-flight checks           
can not mix '--config' with other arguments  
```

The solution is to downgrade to 1.7.0 with the following change in `roles/kubernetes/tasks/apt.yml`:

```yml
- name: Install Packages
  apt:
    name: "{{ item }}"
    force: yes
    state: present
  with_items:
    - kubelet=1.7.0-00
    - kubeadm=1.7.0-00
    - kubectl=1.7.0-00
    - kubernetes-cni
```

After this it works.

The corresponding kubernetes bug is: https://github.com/kubernetes/kubeadm/issues/345

This affects Kubernetes 1.7.1, should be resolved when that update hits the repos.
